# Generated by Django 3.1 on 2021-08-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('orders', '0002_auto_20210828_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprodut',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderprodut',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
